version: "3.9"
services:
  dev:
    build: .
    image: ktchn-app
    command: tail -f /dev/null
    volumes:
      - .:/var/app
      - ./node_modules:/var/app/node_modules
    ports:
      - "3000:3000"
      - "1234:1234"
      - "26166:26168"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - ktchn-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ktchn
      POSTGRES_PASSWORD: localdev

  redis:
    image: redis:6

volumes:
  ktchn-db: